version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "member-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-165uo40l9lng9"
s3_prefix = "member-app"
region = "ap-northeast-2"
profile = "default"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "MasterSecretArn=\"\" MasterSecretsManagerKey=\"\" Stage=\"\""

